FROM redis:6

#RUN mkdir -p /usr/local/etc/redis
#COPY .docker/dev/redis/redis.conf /usr/local/etc/redis/redis.conf

VOLUME /data

EXPOSE 6379

#CMD ["redis-server", "/usr/local/etc/redis/redis.conf"]
CMD ["redis-server"]

