version: "3.8"

networks:
  network:

services:
  nginx:
    image: $IMAGE_NGINX
    ports:
      - $NGINX_PORT:80
      - $NGINX_PORT_SSL:443
    volumes:
      - $STORAGE_DIR/docker/storage/app/public:/var/www/public/storage
    networks:
      - network
#    deploy:
#      placement:
#        constraints: [node.role == manager]
